name: Push-to-EC2
# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - empty
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_KEY_GOOGLE_MAPS: ${{ secrets.VITE_KEY_GOOGLE_MAPS }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_KEY_GOOGLE_MAPS: ${{ secrets.VITE_KEY_GOOGLE_MAPS }}
        with:
          envs: VITE_API_BASE_URL, VITE_KEY_GOOGLE_MAPS
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm use 20
            npm install
            npm run build
            sudo rm -rf /var/www/html/javer-frontend/
            sudo cp -r dist/ /var/www/html/javer-frontend

  slackNotification:
    needs: [deploy]
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
