export const blogPost = {
  id: null,
  blog_id: null,
  language: "es",
  region: "",
  post_author: "por Javer",
  //    post_date: new Date(), use default
  //    post_date_gmt: new Date(),
  post_title: "",
  breadcrumb_title: "",
  post_name: "",
  post_excerpt: "",
  description: "",
  post_content: "",
  post_image1: "/images/blog/default1.jpg",
  post_image2: "/images/blog/default2.jpg",
  post_status: "draft",
  //    post_modified: new Date(),
  //    post_modified_gmt: new Date(),
  version: 1,
  post_content_filtered: "",
  post_type: "post",
  post_mime_type: "text/html",
  permalink: "",
  permalink_hash: "",
};
